CXX = g++ # for cpp compilers we use CXX instead of CC
#CFLAGS = -lm # we don't need link math library, because g++ compiler do it itself

all:
#important to add -std=c++17 for optional class
	$(CXX) -std=c++17 -o main main.cpp
